

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../data/LINEMOD/can/train.txt 
val: ../data/LINEMOD/can/test.txt 
test: ../data/LINEMOD/can/test.txt 

mesh: ../data/LINEMOD/can/can.ply
tr_range: ../data/LINEMOD/can/training_range.txt
backup : ../backup/can
names : ["can"]

background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.202
gpus : 0

nc: 1  # number of classes

fx: 572.4114 
fy: 573.5704
u0: 325.2611
v0: 242.0489

