

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../cube/train.txt 
val: ../cube/val.txt 
test: ../cube/test.txt 

mesh: ../cube/cube.ply
tr_range: ../cube/training_range.txt
backup : ../backup/cube
names : cube

diam : 0.03
gpus : 0

width : 960
height : 960

nc: 1  # number of classes


